### ISSUE TITLE
Fehler beim initialisieren vom Gradle Projekt

### ISSUE THREAD

**Issue by itzmxritz** [theSimpleCloud/SimpleCloud#101]
Da die Velocity Version auf die 3.0.0 oder höher geupgradet werden muss und sie hier auf der 1.? ist, kommen Fehler dass sie nicht gefunden wird

**Comment by FllipEis** [comment]
Hey 👋
welche Service-Version hast du denn ausgewählt?

**Comment by byteinjection** [comment]
Hi. Es ging um das generell erste öffnen des Projektes in IntelliJ nach clone Von GitHub, nicht im Betrieb

**Comment by FllipEis** [comment]
Ah, es ist sowieso ein Update für diese oder nächste Woche geplant. Da werden wir die Velocity Version dann updaten.
Fühl dich frei einen kleinen Pull-Request zu erstellen, ansonsten machen wir das im Laufe der Woche.
