### ISSUE TITLE
Sign Module

### ISSUE THREAD

**Issue by LeD0c4** [theSimpleCloud/SimpleCloud#156]
Hi, 
am i the only one who can't create sign ? 
response : iYopu must look at a sign
I can't do more than to be in front

**Comment by FllipEis** [comment]
Hey, could you please create a short video demonstrating how you create a sign?

**Comment by LeD0c4** [comment]
i do that last time i run the cloud

**Comment by FllipEis** [comment]
I don't understand what you are trying to say. Would be really great if you post a short video or take some screenshots, so we can help you 😄
