### ISSUE TITLE
Could not open settings generic class cache for settings file

### ISSUE THREAD

**Issue by Justman100** [theSimpleCloud/SimpleCloud#173]
Hi, I have the above error!
<br>
[Full Scan](https://scans.gradle.com/s/pwikxxzrq6rmu)

**Comment by Justman100** [comment]
Have it! One must edit `gradle/wrapper/gradle-wrapper.properties` and change

`https\://services.gradle.org/distributions/gradle-8.1.1-bin.zip`
To
`https\://services.gradle.org/distributions/gradle-8.6-rc-1-bin.zip`

**Comment by Justman100** [comment]
But now I have this error:

> Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
<br>
Causing code: `simplecloud-runner/src/main/kotlin/eu/thesimplecloud/runner/RunnerClassLoaderInitMain.kt` in line 95

**Comment by Justman100** [comment]
@FllipEis @Wetterbericht

**Comment by FllipEis** [comment]
Hey, are you getting this error when you are trying to start the runner? If so which `.jar` file are you using?

**Comment by FllipEis** [comment]
> Have it! One must edit `gradle/wrapper/gradle-wrapper.properties` and change
> 
> `https\://services.gradle.org/distributions/gradle-8.1.1-bin.zip` To `https\://services.gradle.org/distributions/gradle-8.6-rc-1-bin.zip`

Would be great, if you try this out with a stable gradle version (not a release candidate) and create a pull request 😄

**Comment by Justman100** [comment]
> Hey, are you getting this error when you are trying to start the runner? If so which `.jar` file are you using?

I have used these commands:
```bash
rm -r simplecloud-plugin/build
rm -r simplecloud-api/build
rm -r simplecloud-modules/simplecloud-module-serviceselection/build
rm -r simplecloud-modules/simplecloud-module-rest/build
rm -r simplecloud-modules/simplecloud-module-statistics/build
rm -r simplecloud-modules/simplecloud-module-hubcommand/build
rm -r simplecloud-modules/simplecloud-module-permission/build
rm -r simplecloud-modules/simplecloud-module-chat-tab/build
rm -r simplecloud-modules/simplecloud-module-internalwrapper/build
rm -r simplecloud-modules/simplecloud-module-cloudflare/build
rm -r simplecloud-modules/simplecloud-module-notify/build
rm -r simplecloud-modules/simplecloud-module-placeholders/build
rm -r simplecloud-modules/simplecloud-module-proxy/build
rm -r simplecloud-modules/build
rm -r simplecloud-modules/simplecloud-module-sign/build
rm -r simplecloud-modules/simplecloud-module-npc/build
rm -r simplecloud-client/build
rm -r simplecloud-base/build
rm -r simplecloud-runner/build
rm -r simplecloud-dependency-loader/build
rm -r build
rm -r simplecloud-launcher/build
rm -r simplecloud-updater/build

bash gradlew clean
bash gradlew build

mkdir -p temp
mkdir temp/modules/
mkdir temp/storage/
cp start-files/*.* temp/
cp simplecloud-modules/**/build/libs/*.jar temp/modules/
cp simplecloud-runner/build/libs/simplecloud-runner-2.7.1.jar temp/runner.jar
cp simplecloud-base/build/libs/simplecloud-base-2.7.1.jar temp/storage/base.jar
cp simplecloud-launcher/build/libs/simplecloud-launcher-2.7.1.jar temp/launcher.jar
# rm temp/modules/SimpleCloud-Chat+Tab.jar
# rm temp/modules/SimpleCloud-ServiceSelection.jar
# rm temp/modules/SimpleCloud-CloudFlare.jar

cd temp
bash start.sh

**Comment by FllipEis** [comment]
What command did you use to build the cloud?

**Comment by Justman100** [comment]
> What command did you use to build the cloud?

Is in the commands list above

**Comment by FllipEis** [comment]
Oh I see, sorry. You have to use `gradlew shadowJar`

**Comment by Justman100** [comment]
> Oh I see, sorry. You have to use `gradlew shadowJar`

Has solved! Thanks 🙂!!!

**Comment by Justman100** [comment]
> > Have it! One must edit `gradle/wrapper/gradle-wrapper.properties` and change
> > `https\://services.gradle.org/distributions/gradle-8.1.1-bin.zip` To `https\://services.gradle.org/distributions/gradle-8.6-rc-1-bin.zip`
> 
> Would be great, if you try this out with a stable gradle version (not a release candidate) and create a pull request 😄

Okay! See #175

**Comment by Justman100** [comment]
@FllipEis

However, when I try to access the dashboard of my SimpleCloud, this is what I get:
> A client connected from an unknown host:

Firefox reflects this:
> Error: Connection interrupted

**Comment by Justman100** [comment]
@FllipEis
