### ISSUE TITLE
Fehler beim Verlassen des Proxys

### ISSUE THREAD

**Issue by JeyVDW** [theSimpleCloud/SimpleCloud#34]
Die Cloud habe ich gerade aufgesetzt und mir lediglich alle Rechte über das Perms-Modul gegeben. Zusätzlich ist keine Gruppe in Wartungen.
Laut Fehlermeldung werde ich vom Server gekickt. Ich verlasse den Server jedoch ganz normal.

Hier der Fehler: https://haste.devcord.xyz/fovacixoqu.md

**Comment by Wetterbericht** [comment]
Der Fehler ist bekannt und wurde auch bereits im dev/2.0 branch behoben. Er entsteht dadurch, dass Waterfall das ServerKickEvent auch beim Disconnecten aufruft. Bei BungeeCord tritt der Fehler nicht auf. Du könntest also bis zum Release der 2.1 einfach BungeeCord verwenden.

**Comment by Wetterbericht** [comment]
Der Fehler ist nun in der 2.1 behoben
