### ISSUE TITLE
Fehler beim Call eines eigenen Events

### ISSUE THREAD

**Issue by JeyVDW** [theSimpleCloud/SimpleCloud#37]
Fehlermeldung im Manager: https://just-paste.it/R75kNj20c2
Event: https://just-paste.it/2EheIF1zn0
Listener (BungeeCord): https://just-paste.it/QMR4bkTzai
Listener (Spigot): https://just-paste.it/khleDSYYtt
Call-Methode (Spigot): https://just-paste.it/Z8lQkm3sBa

Das Event wird in Spigot gecallt; Der Listener in Spigot wird nicht aufgerufen (nur wenn fromPackage `true`); Der Listener in BungeeCord ebenfalls nicht.

**Comment by Foorcee** [comment]
Sorry, but all your paste links are unavailable.

**Comment by FllipEis** [comment]
Invalid
