### ISSUE TITLE
Trotz aktiviert: Bei Wechsel mit /server kommt der Fehler "If you wish to use IP forwarding, please enable it in your Bungeecord config as well"

### ISSUE THREAD

**Issue by lupus0802** [theSimpleCloud/SimpleCloud#52]
Also, ich habe schon sehr viele Anfragen zu dem Fehler gesehen, aber keine hat geholfen. Also frage ich jetzt hier, da ich selber SimpleCloud benutze:
Ich kann ganz normal über meine Bungeecord Proxy joinen und werde auf den Lobbyserver gelassen. Wenn ich allerdings mit /server den Server wechseln möchte, kommt der oben genannte Fehler. Anbei noch meine Bungeecord config und eine "Beispiel" spigot.yml von einem Unterserver.
Wenn ihr noch Informationen braucht, sagt einfach Bescheid.

[YML Dateien.zip](https://github.com/theSimpleCloud/SimpleCloud/files/6983086/YML.Dateien.zip)

(In Textform)
**Beispiel Spigot.yml**

> config-version: 12
> settings:
>   moved-too-quickly-multiplier: 10.0
>   log-villager-deaths: true
>   debug: false
>   save-user-cache-on-stop-only: false
>   moved-wrongly-threshold: 0.0625
>   moved-too-quickly-threshold: 100.0
>   filter-creative-items: true
>   late-bind: false
>   attribute: 
>     maxHealth:
>       max: 2048.0
>     movementSpeed:
>       max: 2048.0
>     attackDamage:
>       max: 2048.0
>   user-cache-size: 0
>   bungeecord: true
>   sample-count: 12
>   int-cache-limit: 1024
>   player-shuffle: 0
>   timeout-time: 60
>   restart-on-crash: true
>   restart-script: ./start.sh
>   netty-threads: 4
> commands:
>   send-namespaced: true
>   tab-complete: 0
>   silent-commandblock-console: false
>   log: true
>   spam-exclusions:
>   - /skill
>   replace-commands:
>   - setblock
>   - summon
>   - testforblock
>   - tellraw
> messages:
>   whitelist: You are not whitelisted on this server!
>   unknown-command: Unknown command. Type "/help" for help.
>   server-full: The server is full!
>   outdated-client: Outdated client! Please use {0}
>   outdated-server: Outdated server! I'm still on {0}
>   restart: Server is restarting
> stats:
>   disable-saving: false
>   forced-stats: {}
> world-settings:
>   default:
>     seed-desert: 14357617
>     seed-igloo: 14357618
>     seed-jungle: 14357619
>     seed-swamp: 14357620
>     seed-monument: 10387313
>     seed-shipwreck: 165745295
>     seed-ocean: 14357621
>     seed-outpost: 165745296
>     seed-endcity: 10387313
>     seed-slime: 987234911
>     seed-bastion: 30084232
>     seed-fortress: 30084232
>     seed-mansion: 10387319
>     seed-fossil: 14357921
>     seed-portal: 34222645
>     view-distance: default
>     trident-despawn-rate: 1200
>     end-portal-sound-radius: 0
>     verbose: true
>     item-despawn-rate: 6000
>     merge-radius:
>       item: 2.5
>       exp: 3.0
>     arrow-despawn-rate: 1200
>     enable-zombie-pigmen-portal-spawns: true
>     wither-spawn-sound-radius: 0
>     chunks-per-tick: 650
>     clear-tick-list: false
>     hanging-tick-frequency: 100
>     mob-spawn-range: 4
>     nerf-spawner-mobs: false
>     growth:
>       beetroot-modifier: 100
>       carrot-modifier: 100
>       potato-modifier: 100
>       vine-modifier: 100
>       cocoa-modifier: 100
>       bamboo-modifier: 100
>       sweetberry-modifier: 100
>       kelp-modifier: 100
>       cactus-modifier: 100
>       cane-modifier: 100
>       melon-modifier: 100
>       mushroom-modifier: 100
>       pumpkin-modifier: 100
>       sapling-modifier: 100
>       wheat-modifier: 100
>       netherwart-modifier: 100
>     entity-activation-range:
>       raiders: 48
>       water: 16
>       villagers: 32
>       flying-monsters: 32
>       villagers-work-immunity-after: 100
>       villagers-work-immunity-for: 20
>       villagers-active-for-panic: true
>       tick-inactive-villagers: true
>       animals: 32
>       monsters: 32
>       misc: 16
>       wake-up-inactive:
>         animals-max-per-tick: 4
>         animals-every: 1200
>         animals-for: 100
>         monsters-max-per-tick: 8
>         monsters-every: 400
>         monsters-for: 100
>         villagers-max-per-tick: 4
>         villagers-every: 600
>         villagers-for: 100
>         flying-monsters-max-per-tick: 8
>         flying-monsters-every: 200
>         flying-monsters-for: 100
>     entity-tracking-range:
>       players: 48
>       animals: 48
>       monsters: 48
>       misc: 32
>       other: 64
>     anti-xray:
>       enabled: true
>       engine-mode: 1
>       hide-blocks:
>       - 14
>       - 15
>       - 16
>       - 21
>       - 48
>       - 49
>       - 54
>       - 56
>       - 73
>       - 74
>       - 82
>       - 129
>       - 130
>       replace-blocks:
>       - 1
>       - 5
>     save-structure-info: true
>     max-tnt-per-tick: 100
>     ticks-per:
>       hopper-transfer: 8
>       hopper-check: 1
>     hopper-amount: 1
>     random-light-updates: false
>     hunger:
>       jump-walk-exhaustion: 0.05
>       jump-sprint-exhaustion: 0.2
>       swim-multiplier: 0.01
>       sprint-multiplier: 0.1
>       other-multiplier: 0.0
>       combat-exhaustion: 0.1
>       regen-exhaustion: 6.0
>     max-tick-time:
>       tile: 50
>       entity: 50
>     max-bulk-chunks: 10
>     zombie-aggressive-towards-villager: true
>     dragon-death-sound-radius: 0
>     seed-village: 10387312
>     seed-feature: 14357617
>     max-entity-collisions: 8
>     squid-spawn-range:
>       min: 45.0
> advancements:
>   disable-saving: false
>   disabled:
>   - minecraft:story/disabled
> players:
>   disable-saving: false
> 

**Bungeecord Config**

> listeners:
> - query_port: 25577
>   motd: '&1Ein Server'
>   tab_list: GLOBAL_PING
>   query_enabled: false
>   proxy_protocol: false
>   forced_hosts:
>     pvp.md-5.net: pvp
>   ping_passthrough: false
>   priorities:
>   - lobby
>   bind_local_address: false
>   host: 0.0.0.0:25565
>   max_players: 100
>   tab_size: 60
>   force_default_server: false
> remote_ping_cache: -1
> network_compression_threshold: 256
> permissions:
>   default:
>   - bungeecord.command.server
>   - bungeecord.command.list
>   admin:
>   - bungeecord.command.alert
>   - bungeecord.command.end
>   - bungeecord.command.ip
>   - bungeecord.command.reload
> log_pings: true
> connection_throttle_limit: 3
> server_connect_timeout: 5000
> timeout: 30000
> stats: a83781af-9bc4-48a0-b5d1-66367af0966b
> player_limit: -1
> ip_forward: true
> groups:
>   md_5:
>   - admin
> remote_ping_timeout: 5000
> connection_throttle: -1
> log_commands: false
> prevent_proxy_connections: false
> online_mode: true
> forge_support: false
> disabled_commands:
> - disabledcommandhere
> servers:
>   lobby:
>     motd: '&1Another Bungee server'
>     address: localhost:25565
>     restricted: false
>   testserver:
>     motd: '&1Ein Server'
>     adress: localhost:50001
>     restriced: false
>     address: localhost:25565
>     restricted: false
>   building:
>     motd: '&1Ein Server'
>     adress: localhost:50003
>     restriced: false
>     address: localhost:25565
>     restricted: false
>   citybuild:
>     motd: '&1Ein Server'
>     adress: localhost:50001
>     restriced: false
>     address: localhost:25565
>     restricted: false

**Comment by JeyVDW** [comment]
Hey,

im Normalfall sollte die Funktion automatisch aktiviert werden. In welchem Ordner hast du denn die BungeeCord-Config? Kannst du uns dazu einfach mal den kompletten Pfad ab dem Hauptverzeichnis von SimpleCloud nennen?

Viele Grüße
Jerome

**Comment by lupus0802** [comment]
Das ganze hat sich schon erledigt, ich habe einfach vergessen den thread zu schließen (Entschuldigung dafür). Eine Neuinstallation hat geholfen.
