### ISSUE TITLE
Unknown Command Bug

### ISSUE THREAD

**Issue by Gaunercools** [theSimpleCloud/SimpleCloud#65]
Hi,
ich habe den Bug, dass man manchmal wenn man beim Hub-Module "/l , /hub oder /lobby" macht die Nachricht "Unknown command. Type "/help" for help." erscheint. 

Ich nutze die Cloud Version 2.2.

**Comment by JeyVDW** [comment]
Hast du den Fehler auch bei der neusten Version?

**Comment by ClientDNS** [comment]
Ziemliche Inaktivität hier.

**Comment by FllipEis** [comment]
Inactive.
