### ISSUE TITLE
Serverversion

### ISSUE THREAD

**Issue by xxFLORII** [theSimpleCloud/SimpleCloud#67]
Gibt es die möglichkeit vielleicht auch Support für die Serversoftwares *Nukkit* & *WaterdogPE* ( Proxy ) hinzuzufügen? Sind beide für die Minecraft Bedrockedition.

**Comment by Wetterbericht** [comment]
Das wird in dieser Version nicht mehr passieren, in der v3 wird Nukkit und Waterdog sehr wahrscheinlich drin sein.
