### ISSUE TITLE
Fehler (PacketIOCallEvent) beim stoppen einer (Paper/Spigot) Instanz

### ISSUE THREAD

**Issue by TGamings** [theSimpleCloud/SimpleCloud#95]
Cloud-Version: 2.4.1
Server-Version: Paper-1.19
Proxy-Version: Velocity-1.19

Ablauf des Fehlers:
Wenn man eine Spigot/Paper Instanz mit /stop oder über die Konsole stoppt UND mindestens ein Spieler auf dieser Instanz ist, kommt folgender Fehler:

![image](https://user-images.githubusercontent.com/44941489/182028123-0f4b68a8-083a-4bf4-8c50-246d5e5afce8.png)

**Comment by FllipEis** [comment]
Pretty sure this is fixed by now
